theme: jekyll-theme-midnight
title: Welcome to Aalok's GitHub Page!
description: Here I will periodic post what's on my mind. I'm sure you'd like to return here someday, so please feel free to bookmark this page to keep an eye on my updates.
